[build-system]
requires = ['setuptools>=61.0', 'setuptools-scm']  # Require setuptools >= 61.0
build-backend = 'setuptools.build_meta'

[tool.setuptools]
packages = ["improvelib"]

[project]
name = 'improvelib'
version = '0.1.0'  # Corrected version format
authors = [
    { "Alexander Partin <apartin@anl.gov>"},
    { "Andreas Wilke <wilke@anl.gov>"},
    { "Natasha Koussa" },
    { "Sara Jones" },
    { "Priyanka Vasanthakumari <pvasanthakumari@anl.gov>" },
    { "Oleksandr Narykov <onarykov@anl.gov>"},
    { "Rajeev Jain <rajeeja@gmail.com>"},
    { "Justin M Wozniak <woz@anl.gov>"},
    { "Rylie Weaver" }
]
description = 'Open-source package for model standardization and comparison in Python'
readme = 'README_PyPi.md'
requires-python = '>=3.6'
classifiers = [
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'Topic :: Software Development :: Libraries',
]

dependencies = [
  "pandas",
  "requests",
  "tqdm",
  "typing_extensions",
  "pyyaml",
  "scikit-learn"
]

[project.urls]
Homepage = 'https://github.com/JDACS4C-IMPROVE/IMPROVE'
Issues = 'https://github.com/JDACS4C-IMPROVE/IMPROVE/issues'
Documentation = 'https://jdacs4c-improve.github.io/docs/'
