[CSA]
#input_dir = <PATH/TO/CSA/DATA>
#output_dir = <PATH/TO/SAVE/CSA>
#model_scripts_dir = <PATH/TO/MODEL/DIR>
#model_name = <MODEL_NAME>
#model_environment = <NAME_OF_MODEL_ENV>
#preprocess_args = {}
#train_args = {}
#infer_args = {}



# Small experiment
source_datasets = ["CCLE", "gCSI"]
target_datasets = ["CCLE", "gCSI"]
split_nums = ["0","1"]
only_cross_study = False

# Full-scale experiment
; csa_outdir = ./bruteforce_exp_fullscale
; source_datasets = ["CCLE", "CTRPv2", "gCSI", "GDSCv1", "GDSCv2"]
; target_datasets = ["CCLE", "CTRPv2", "gCSI", "GDSCv1", "GDSCv2"]
; split_nums = ["0","1","2","3","4","5","6","7","8","9"]
; only_cross_study = False



