[DEFAULT]
input_dir = ./csa_data/raw_data
y_col_name = auc
use_singularity = False
singularity_image = path_to_your_singularity_container.sif
hyperparameters_file = ./hyperparameters_default.json
model_name = graphdrp
model_scripts_dir = /app/GraphDRP
model_environment = graphdrp
only_cross_study = False
epochs = 200
input_supp_data_dir = ''

; # Exp 3
output_dir = ./parsl_csa_gcsi
source_datasets = ["gCSI"]
target_datasets = ["gCSI"]
split = ["0"]

[Preprocess]

[Train]

[Infer]
