[RANDOMIZE]
#input_dir = <PATH/TO/CSA/DATA>
#output_dir = <PATH/TO/SAVE/CSA>
#model_scripts_dir = <PATH/TO/MODEL/DIR>
#model_name = <MODEL_NAME>
#randomized_data_dir = <PATH/TO/RANDOMIZED/DATA>
#randomized_data = {}
#preprocess_args = {}
#train_args = {}
#infer_args = {}


# Small experiment
datasets = ["CCLE", "gCSI"]
split_nums = ["0","1"]
#split_types = ["split"]


